library_project/api/urls.py
from django.urls import include, path
from rest_framework.authtoken import views
from rest_framework.routers import SimpleRouter

from .views import BookViewset, SignUpView
from .yasg import urlpatterns as doc_urls

router = SimpleRouter()
router.register("books", BookViewset)


auth_patterns = [
    path("token/", views.obtain_auth_token),
    path("signup/", SignUpView.as_view()),
]

urlpatterns = [
    path("", include(router.urls)),
    path("auth/", include(auth_patterns)),
    path("docs/", include(doc_urls)),
]

library_project/library/urls.py
from django.urls import path

from .views import DebtListView, IndexView, ReaderBooksView

app_name = "library"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("reader_books/", ReaderBooksView.as_view(), name="reader_books"),
    path("debt/", DebtListView.as_view(), name="debt"),
]

library_project/library_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("library.urls")),
    path("admin/", admin.site.urls),
    path("users/", include("user.urls")),
    path("api/", include("api.urls")),
]

library_project/user/urls.py
from django.urls import include, path

from .views import CreateCustomUserView

app_name = "auth"

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path(
        "registration/",
        CreateCustomUserView.as_view(),
        name="registration",
    ),
]

library_project/templates/includes/footer.html
<footer>
  <center>
    <p>@Тестовое для БериРубли</p>
  </center>
</footer>

library_project/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar shadow-sm">
    <div class="container">
      {% with request.resolver_math.view_name as view_name %}
        <ul class="nav nav-pills ">
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'library:index' %} active {% endif %}"
              href="{% url 'library:index' %}"
            >
              Главная
            </a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a href="{% url 'library:reader_books' %}" class="nav-link">{{ user.username }}</a>
            </li>
            <li class="nav-item">
              <form action="{% url 'auth:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">Выйти</button>
              </form>
            </li>
            {% if user.is_librarian %}
              <li class="nav-item"><a href="{% url 'library:debt' %}" class="nav-link">Должники</a></li>
            {% endif %}
          {% else %}
            <li class="nav-item">
              <a class="nav-link {% if view_name == 'login' %} active {% endif %}"
                href="{% url 'auth:login' %}" 
              >
                Войти
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if view_name == 'registration' %} active {% endif %}"
                href="{% url 'auth:registration' %}" 
              >
                Регистрация
              </a>
            </li>
          {% endif %}
        </ul>
      {% endwith %}
    </div>
  </nav>
</header>